# Generated by Django 5.0.6 on 2024-05-16 08:27

import site_setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس سایت')),
            ],
        ),
        migrations.CreateModel(
            name='SiteLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_light', models.ImageField(upload_to=site_setting.models.CustomLogoName('assets/images/logo/', 'light'), verbose_name='لوگو مود لایت')),
                ('logo_dark', models.ImageField(upload_to=site_setting.models.CustomLogoName('assets/images/logo/', 'dark'), verbose_name='لوگو مود دارک')),
            ],
        ),
        migrations.CreateModel(
            name='SitePhoneNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNum', models.CharField(max_length=100, verbose_name='تلفن سایت')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialMediaLink', models.CharField(max_length=100, verbose_name='شبکه های اجتماعی سایت')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل سایت')),
                ('site_address', models.ManyToManyField(blank=True, null=True, to='site_setting.siteaddress', verbose_name='آدرس سایت')),
                ('site_logo', models.ManyToManyField(blank=True, null=True, to='site_setting.sitelogos', verbose_name='لوگو سایت')),
                ('site_phoneNum', models.ManyToManyField(blank=True, null=True, to='site_setting.sitephonenum', verbose_name='تلفن سایت')),
                ('site_socialMedia', models.ManyToManyField(blank=True, null=True, to='site_setting.sitesocialmedia', verbose_name='شبکه های اجتماعی سایت')),
            ],
        ),
    ]
