# Generated by Django 5.0.6 on 2024-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesocialmedia',
            name='SocialMediaName',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Linkdin', 'Linkdin'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram')], default='نام شبکه اجتماعی ', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesocialmedia',
            name='SocialMediaLink',
            field=models.CharField(max_length=100, verbose_name='لینک شبکه های اجتماعی '),
        ),
    ]
