# Generated by Django 5.0.6 on 2024-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_sitesocialmedia_socialmedianame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesocialmedia',
            name='SocialMediaName',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Linkdin', 'Linkdin'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram')], max_length=20, verbose_name='نام شبکه اجتماعی '),
        ),
    ]
