# Generated by Django 5.0.6 on 2024-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_alter_sitesocialmedia_socialmedianame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteaddress',
            name='address',
            field=models.CharField(max_length=100, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitephonenum',
            name='PhoneNum',
            field=models.CharField(max_length=100, verbose_name='تلفن'),
        ),
    ]
